TRAIN_DATA = [

# ===================== DRINK =====================
# ===== Positive =====
("nước rất ngon", "drink", 1),
("uống rất đã", "drink", 1),
("trà sữa béo vừa phải", "drink", 1),
("vị ngọt thanh dễ uống", "drink", 1),
("cafe thơm và đậm", "drink", 1),
("nước pha vừa miệng", "drink", 1),
("uống hoài không ngán", "drink", 1),
("vị trà rõ", "drink", 1),
("cafe uống rất ổn", "drink", 1),
("nước ngon hơn mong đợi", "drink", 1),
("trà sữa siêu ngon", "drink", 1),
("đồ uống được phục vụ nhanh, vẫn giữ nhiệt độ chuẩn", "drink", 1),
("trà hoa quả mix sáng tạo, vừa miệng", "drink", 1),
("cafe hạt xịn, rang mới thơm nức", "drink", 1),
("cocktail độc đáo, vừa uống vừa thưởng thức", "drink", 1),
("smoothie từ trái cây nhập khẩu, uống cực đã", "drink", 1),
("uống nước xong thấy rất sảng khoái", "drink", 1),
("cafe thơm nức, cực kỳ ngon", "drink", 1),
("vị nước vừa miệng, không quá ngọt", "drink", 1),
("cocktail pha rất chuẩn", "drink", 1),
("nước ép trái cây tươi và ngọt", "drink", 1),
("sinh tố ngon, rất đáng thử", "drink", 1),
("đồ uống pha chế chuyên nghiệp", "drink", 1),
("matcha latte thơm và ngon", "drink", 1),
("nước mát lạnh, uống cực đã", "drink", 1),
("smoothie tươi ngon", "drink", 1),
("cafe latte mịn và thơm", "drink", 1),
("trà hoa quả rất hợp khẩu vị", "drink", 1),
("nước ép vừa chua vừa ngọt dễ chịu", "drink", 1),
("đồ uống được trang trí đẹp mắt", "drink", 1),
("nước ngon, uống vào thấy sảng khoái", "drink", 1),
("trà sữa vừa ngọt vừa béo", "drink", 1),
("matcha latte rất thơm và đậm", "drink", 1),
("sinh tố uống xong cảm giác tươi mát", "drink", 1),
("cafe đậm, uống cực thích", "drink", 1),
("cocktail ngon tuyệt vời", "drink", 1),
("nước ép trái cây tự nhiên, ngọt vừa", "drink", 1),
("trà tươi pha ngon", "drink", 1),
("uống nước thấy rất thoải mái", "drink", 1),
("cafe pha đúng gu", "drink", 1),
("trà sữa chuẩn vị", "drink", 1),
("cocktail hợp khẩu vị", "drink", 1),
("matcha latte béo vừa phải, thơm ngon", "drink", 1),
("smoothie tươi mát, uống rất thích", "drink", 1),
("nước uống pha ngon, hợp miệng", "drink", 1),
("trà sữa ngon không quá ngọt", "drink", 1),
("cafe rang xay thơm nức", "drink", 1),
("cocktail mát lạnh, uống cực đã", "drink", 1),
("sinh tố ngon, vị tự nhiên", "drink", 1),
("nước ép ngon, vừa miệng", "drink", 1),
("matcha latte cực ngon, thơm", "drink", 1),
("trà sữa uống xong muốn gọi thêm", "drink", 1),
("cafe uống rất ổn, không đắng quá", "drink", 1),
("cocktail ngon, uống dễ chịu", "drink", 1),
("smoothie vừa miệng, ngọt vừa phải", "drink", 1),
("nước mát, uống cực thích", "drink", 1),
("trà tươi ngon, thơm nhẹ", "drink", 1),
("cafe latte béo vừa phải", "drink", 1),
("cocktail ngon, chuẩn vị", "drink", 1),
("sinh tố rất ngon, đáng thử", "drink", 1),
("nước ép ngon, tươi mát", "drink", 1),
("matcha latte thơm, uống sướng", "drink", 1),
("trà sữa uống rất thích", "drink", 1),
("cafe đậm, thơm, vừa miệng", "drink", 1),
("smoothie ngon, uống thấy tươi mát", "drink", 1),
("cocktail ngon, mát lạnh", "drink", 1),
("nước ép tự nhiên, ngon tuyệt", "drink", 1),
("trà pha ngon, vừa miệng", "drink", 1),
("cafe latte mịn, thơm", "drink", 1),
("sinh tố tươi, uống sảng khoái", "drink", 1),
("matcha latte ngon, vị đậm", "drink", 1),
("cocktail ngon, chuẩn gu", "drink", 1),
("trà sữa thơm, béo vừa", "drink", 1),
("nước ngon, uống dễ chịu", "drink", 1),
("smoothie uống xong thấy tươi mát", "drink", 1),
("cafe thơm, uống thích", "drink", 1),
("trà hoa quả ngon, dễ uống", "drink", 1),
("nước ép thơm, ngọt vừa", "drink", 1),
("cocktail ngon, mát", "drink", 1),
("matcha latte uống cực thích", "drink", 1),
("smoothie vừa miệng, ngon", "drink", 1),
("cafe đậm, uống sảng khoái", "drink", 1),
("trà sữa ngon, vị vừa", "drink", 1),
("nước mát lạnh, uống thích", "drink", 1),
("cocktail tươi mát, ngon", "drink", 1),
("sinh tố ngon, vị tự nhiên", "drink", 1),
("nước ép ngon, uống dễ chịu", "drink", 1),
("matcha latte thơm, uống thích", "drink", 1),
("trà sữa ngon, hợp khẩu vị", "drink", 1),
("cafe latte ngon, vị vừa phải", "drink", 1),
("cocktail mát lạnh, vị chuẩn", "drink", 1),
("smoothie tươi ngon, đáng thử", "drink", 1),
("nước ép tươi ngon, vừa miệng", "drink", 1),
("matcha latte thơm, vừa uống", "drink", 1),
("trà sữa ngon, uống mê luôn", "drink", 1),
("cafe thơm, uống thích", "drink", 1),
("cocktail ngon, vừa miệng", "drink", 1),
("sinh tố ngon, tươi mát", "drink", 1),
("nước mát, uống sảng khoái", "drink", 1),
("trà tươi ngon, uống rất thích", "drink", 1),
("cafe latte thơm, vị chuẩn", "drink", 1),
("smoothie vừa miệng, ngon tuyệt", "drink", 1),
("cocktail tươi, ngon", "drink", 1),
("nước ép ngon, vừa miệng", "drink", 1),
("matcha latte uống sướng", "drink", 1),
("trà sữa ngon, vị đậm", "drink", 1),
("cafe uống cực thích", "drink", 1),
("cocktail mát, vừa miệng", "drink", 1),
("smoothie thơm ngon, uống sảng khoái", "drink", 1),
("nước ép ngon, hợp khẩu vị", "drink", 1),
("matcha latte ngon, thơm vừa", "drink", 1),
("trà sữa thơm, vừa uống", "drink", 1),
("cafe ngon, uống dễ chịu", "drink", 1),
("cocktail ngon, uống tươi mát", "drink", 1),
("smoothie ngon, vị tự nhiên", "drink", 1),
("nước mát lạnh, cực thích", "drink", 1),
("trà tươi ngon, uống sảng khoái", "drink", 1),
("cafe latte thơm, uống mê", "drink", 1),
("smoothie ngon, vừa miệng", "drink", 1),
("cocktail ngon, vị dễ chịu", "drink", 1),
("nước ép tươi ngon, uống thích", "drink", 1),
("matcha latte ngon, uống thích", "drink", 1),
("trà sữa ngon, vừa miệng", "drink", 1),
("cafe thơm, uống cực thích", "drink", 1),
("menu đa dạng, nhiều món lựa chọn", "drink", 1),
("nước ngon, chuẩn vị, pha vừa miệng", "drink", 1),
("có nhiều loại đồ uống mới lạ, sáng tạo", "drink", 1),
("đồ ăn và nước uống chất lượng, tươi ngon", "drink", 1),
("đồ uống tươi, nguyên liệu sạch và ngon", "drink", 1),
("trà sữa được trang trí rất đẹp mắt", "drink", 1),
("nước ép trái cây thơm, uống cực sảng khoái", "drink", 1),
("cafe pha chuẩn, không quá đắng", "drink", 1),
("uống nước thấy tươi mát, rất thích", "drink", 1),
("cocktail lên nhanh, vừa vị, ngon", "drink", 1),
("matcha latte béo và thơm, uống sướng", "drink", 1),
("smoothie pha đều, vị tự nhiên, ngon", "drink", 1),
("đồ uống được phục vụ nhanh, vẫn giữ nhiệt độ chuẩn", "drink", 1),
("trà hoa quả vừa miệng, topping đầy đủ", "drink", 1),

# ===== Neutral =====
("uống cũng được", "drink", 0),
("vị nước bình thường", "drink", 0),
("chất lượng ở mức ổn", "drink", 0),
("không quá ngon cũng không dở", "drink", 0),
("uống tạm ổn", "drink", 0),
("vị quen thuộc", "drink", 0),
("không gây ấn tượng", "drink", 0),
("nước không quá ngọt", "drink", 0),
("uống được trong tầm giá", "drink", 0),
("không có gì đặc biệt", "drink", 0),
("ngon nhưng không xuất sắc", "drink", 0),
("trà sữa bình thường", "drink", 0),
("nước uống không quá nổi bật", "drink", 0),
("vị ổn nhưng không đặc sắc", "drink", 0),
("cocktail bình thường", "drink", 0),
("đồ uống vừa miệng, chấp nhận được", "drink", 0),
("matcha latte ổn", "drink", 0),
("nước ép bình thường", "drink", 0),
("sinh tố uống được", "drink", 0),
("đồ uống không tệ cũng không ngon", "drink", 0),
("uống được, không tệ", "drink", 0),
("vị nước ổn", "drink", 0),
("không quá ngon nhưng cũng không dở", "drink", 0),
("trà sữa bình thường", "drink", 0),
("cafe uống tạm", "drink", 0),
("nước pha vừa phải", "drink", 0),
("uống xong không cảm nhận gì đặc biệt", "drink", 0),
("smoothie ổn, không quá nổi bật", "drink", 0),
("cocktail bình thường", "drink", 0),
("matcha latte uống được", "drink", 0),
("vị nước khá ổn", "drink", 0),
("cafe uống vừa miệng", "drink", 0),
("trà pha tạm", "drink", 0),
("nước ép uống được", "drink", 0),
("uống thấy bình thường", "drink", 0),
("smoothie uống vừa phải", "drink", 0),
("cocktail ổn, không xuất sắc", "drink", 0),
("trà sữa tạm ổn", "drink", 0),
("nước pha vừa đủ", "drink", 0),
("matcha latte bình thường", "drink", 0),
("uống được, không nổi bật", "drink", 0),
("cafe uống ổn nhưng không xuất sắc", "drink", 0),
("trà sữa uống vừa phải", "drink", 0),
("nước uống đủ dùng", "drink", 0),
("smoothie không quá ngọt cũng không nhạt", "drink", 0),
("cocktail không tệ, không xuất sắc", "drink", 0),
("vị nước vừa miệng", "drink", 0),
("cafe tạm được", "drink", 0),
("trà sữa vừa phải, không đặc sắc", "drink", 0),
("uống được, không ấn tượng", "drink", 0),
("smoothie uống vừa phải", "drink", 0),
("cocktail tạm ổn", "drink", 0),
("matcha latte uống được", "drink", 0),
("vị nước bình thường", "drink", 0),
("cafe uống tạm ổn", "drink", 0),
("trà sữa uống được, không nổi bật", "drink", 0),
("nước pha bình thường", "drink", 0),
("smoothie uống được", "drink", 0),
("cocktail không quá đặc biệt", "drink", 0),
("matcha latte ổn", "drink", 0),
("uống bình thường", "drink", 0),
("cafe bình thường", "drink", 0),
("trà sữa không nổi bật", "drink", 0),
("nước pha vừa phải, không tệ", "drink", 0),
("smoothie ổn nhưng không đặc sắc", "drink", 0),
("cocktail bình thường, uống được", "drink", 0),
("vị nước tạm ổn", "drink", 0),
("cafe uống được, không quá đặc biệt", "drink", 0),
("trà sữa vừa uống được", "drink", 0),
("nước uống bình thường", "drink", 0),
("smoothie không tệ", "drink", 0),
("cocktail ổn", "drink", 0),
("matcha latte bình thường", "drink", 0),
("uống vừa phải", "drink", 0),
("cafe ổn, không đặc sắc", "drink", 0),
("trà sữa ổn", "drink", 0),
("nước uống vừa phải", "drink", 0),
("smoothie uống được", "drink", 0),
("cocktail tạm ổn", "drink", 0),
("matcha latte uống tạm", "drink", 0),
("vị nước uống được", "drink", 0),
("cafe tạm ổn", "drink", 0),
("trà sữa bình thường", "drink", 0),
("nước pha ổn", "drink", 0),
("smoothie uống được, không đặc sắc", "drink", 0),
("cocktail bình thường", "drink", 0),
("matcha latte vừa uống được", "drink", 0),
("uống được, không tệ", "drink", 0),
("cafe vừa uống được", "drink", 0),
("trà sữa tạm ổn", "drink", 0),
("nước bình thường", "drink", 0),
("smoothie ổn, không nổi bật", "drink", 0),
("cocktail uống được", "drink", 0),
("matcha latte bình thường", "drink", 0),
("uống tạm ổn", "drink", 0),
("cafe uống được, không đặc sắc", "drink", 0),
("trà sữa bình thường", "drink", 0),
("nước uống vừa miệng", "drink", 0),
("smoothie bình thường", "drink", 0),
("cocktail tạm ổn", "drink", 0),
("matcha latte vừa uống được", "drink", 0),
("vị nước tạm ổn", "drink", 0),
("cafe bình thường", "drink", 0),
("trà sữa uống vừa phải", "drink", 0),
("nước uống ổn", "drink", 0),
("smoothie uống được", "drink", 0),
("cocktail bình thường", "drink", 0),
("matcha latte ổn", "drink", 0),
("uống được, bình thường", "drink", 0),
("cafe uống được", "drink", 0),
("trà sữa tạm ổn", "drink", 0),
("nước pha vừa phải", "drink", 0),
("smoothie ổn", "drink", 0),
("cocktail uống được", "drink", 0),
("matcha latte bình thường", "drink", 0),
("menu bình thường, không quá đa dạng", "drink", 0),
("nước uống vừa ổn, không đặc sắc lắm", "drink", 0),
("đồ ăn đủ dùng nhưng không quá ấn tượng", "drink", 0),
("trà sữa ngon nhưng hơi nhạt", "drink", 0),
("cafe ổn, không thơm bằng quán khác", "drink", 0),
("nước uống vừa miệng nhưng topping hơi ít", "drink", 0),
("smoothie ngon nhưng không quá đặc sắc", "drink", 0),
("cocktail bình thường, vị hơi nhạt", "drink", 0),
("matcha latte uống được, không quá ấn tượng", "drink", 0),
("trà tươi ngon, nhưng không nổi bật so với giá tiền", "drink", 0),
("nước ép vừa đủ uống, không quá tươi", "drink", 0),
("đồ uống pha nhanh nhưng không quá ngon", "drink", 0),
("trà sữa uống vừa phải, không quá béo", "drink", 0),
("trà sữa uống được nhưng topping hơi ít", "drink", 0),
("smoothie ngon nhưng không quá đặc sắc", "drink", 0),
("cafe ổn, không thơm bằng quán khác", "drink", 0),
("nước ép vừa đủ uống, không quá tươi", "drink", 0),
("cocktail bình thường, vị hơi nhạt", "drink", 0),

# ===== Negative =====
("nước dở", "drink", -1),
("uống không ngon", "drink", -1),
("vị rất tệ", "drink", -1),
("trà sữa nhạt", "drink", -1),
("cafe bị cháy", "drink", -1),
("nước quá ngọt", "drink", -1),
("uống rất khó chịu", "drink", -1),
("vị lạ khó uống", "drink", -1),
("nước pha dở", "drink", -1),
("uống không nổi", "drink", -1),
("nước không ngon", "drink", -1),
("không phải là ngon", "drink", -1),
("uống không hề ngon", "drink", -1),
("trà sữa nhạt nhẽo", "drink", -1),
("nước ép hỏng", "drink", -1),
("cafe bị mặn hoặc cháy", "drink", -1),
("sinh tố quá nhạt", "drink", -1),
("cocktail quá chua", "drink", -1),
("đồ uống không hợp khẩu vị", "drink", -1),
("uống xong thấy khó chịu", "drink", -1),
("nước nhạt nhẽo, không ngon", "drink", -1),
("uống vào thấy hôi, khó chịu", "drink", -1),
("cafe bị đắng quá mức", "drink", -1),
("trà sữa quá ngọt, khó uống", "drink", -1),
("nước ép quá chua", "drink", -1),
("smoothie không mịn, khó nuốt", "drink", -1),
("cocktail nhạt, không vị", "drink", -1),
("matcha latte quá đắng", "drink", -1),
("trà pha nhạt, không thơm", "drink", -1),
("nước uống bị lợ, không tươi", "drink", -1),
("cafe pha quá đặc, khó uống", "drink", -1),
("sinh tố quá ngọt, làm mình mệt", "drink", -1),
("trà sữa bị loãng, không ngon", "drink", -1),
("cocktail không cân bằng vị", "drink", -1),
("nước ép bị đắng, khó uống", "drink", -1),
("smoothie pha cẩu thả, không ngon", "drink", -1),
("cafe quá nhạt, thiếu mùi thơm", "drink", -1),
("trà hoa quả bị hỏng vị", "drink", -1),
("nước mát không mát, hơi ấm", "drink", -1),
("cocktail có vị lạ, khó uống", "drink", -1),
("matcha latte quá loãng, nhạt", "drink", -1),
("trà sữa không béo, nhạt nhẽo", "drink", -1),
("smoothie quá nhạt, mất hứng", "drink", -1),
("nước ép lợ, không ngon", "drink", -1),
("cafe bị cháy, đắng quá mức", "drink", -1),
("trà pha quá nhạt", "drink", -1),
("cocktail quá ngọt, không dễ uống", "drink", -1),
("sinh tố có vị lạ", "drink", -1),
("nước uống nhạt, không hương vị", "drink", -1),
("trà sữa không đáng tiền", "drink", -1),
("matcha latte quá đắng và nhạt", "drink", -1),
("cafe rang khét, uống khó chịu", "drink", -1),
("cocktail không tươi, vị kì lạ", "drink", -1),
("smoothie quá loãng, không ngon", "drink", -1),
("nước ép pha cẩu thả, chua quá", "drink", -1),
("trà tươi pha nhạt", "drink", -1),
("cafe latte quá nhạt", "drink", -1),
("smoothie bị hỏng vị, khó uống", "drink", -1),
("cocktail quá nhạt, không hợp khẩu vị", "drink", -1),
("nước ép bị hỏng, lạ vị", "drink", -1),
("trà sữa quá loãng", "drink", -1),
("cafe quá đắng, không uống được", "drink", -1),
("smoothie quá ngọt, mất ngon", "drink", -1),
("nước uống có mùi lạ", "drink", -1),
("cocktail quá cồn, khó uống", "drink", -1),
("matcha latte không thơm, nhạt nhẽo", "drink", -1),
("trà sữa bị tách lớp", "drink", -1),
("nước ép nhạt nhẽo, không ngon", "drink", -1),
("cafe pha cẩu thả, vị lạ", "drink", -1),
("smoothie uống xong khó chịu", "drink", -1),
("cocktail pha không đều", "drink", -1),
("nước uống quá ngọt, gắt cổ", "drink", -1),
("trà sữa có mùi lạ", "drink", -1),
("cafe bị mặn hoặc quá đắng", "drink", -1),
("smoothie loãng và nhạt", "drink", -1),
("nước ép quá chua, khó uống", "drink", -1),
("cocktail quá nhạt, không ngon", "drink", -1),
("matcha latte nhạt, không thơm", "drink", -1),
("trà sữa pha cẩu thả, mất ngon", "drink", -1),
("cafe rang quá khét, đắng", "drink", -1),
("smoothie quá đặc, khó uống", "drink", -1),
("nước uống nhạt, không hứng thú", "drink", -1),
("cocktail quá ngọt, mất cân bằng", "drink", -1),
("trà sữa quá nhạt và lợ", "drink", -1),
("matcha latte không ngon, nhạt", "drink", -1),
("cafe quá nhạt, không đáng tiền", "drink", -1),
("smoothie pha quá lỏng, nhạt", "drink", -1),
("nước ép quá lợ, uống khó chịu", "drink", -1),
("cocktail quá chua và nhạt", "drink", -1),
("trà sữa không thơm, nhạt", "drink", -1),
("cafe quá đắng, uống không được", "drink", -1),
("smoothie không ngon, nhạt", "drink", -1),
("nước ép nhạt nhẽo, mất vị", "drink", -1),
("cocktail nhạt, không hợp gu", "drink", -1),
("matcha latte quá nhạt, khó uống", "drink", -1),
("trà sữa uống xong thất vọng", "drink", -1),
("cafe pha không ngon", "drink", -1),
("smoothie lợ, khó chịu", "drink", -1),
("nước uống quá đắng", "drink", -1),
("cocktail không ngon, nhạt nhẽo", "drink", -1),
("matcha latte pha nhạt, mất vị", "drink", -1),
("trà sữa không đáng tiền", "drink", -1),
("cafe rang cháy, uống khó chịu", "drink", -1),
("smoothie nhạt nhẽo, không ngon", "drink", -1),
("nước ép lợ, khó uống", "drink", -1),
("cocktail quá ngọt và nhạt", "drink", -1),
("matcha latte quá đắng, khó uống", "drink", -1),
("trà sữa pha quá nhạt", "drink", -1),
("cafe không thơm, uống nhạt", "drink", -1),
("smoothie uống xong không hài lòng", "drink", -1),
("nước uống quá chua, khó uống", "drink", -1),
("cocktail nhạt, không ngon", "drink", -1),
("matcha latte nhạt nhẽo, khó uống", "drink", -1),
("trà sữa nhạt, không đáng tiền", "drink", -1),
("cafe quá đắng, mất vị", "drink", -1),
("smoothie pha quá nhạt", "drink", -1),
("nước ép bị nhạt, không ngon", "drink", -1),
("cocktail quá nhạt, mất vị", "drink", -1),
("matcha latte nhạt nhẽo, mất hứng", "drink", -1),
("trà sữa quá nhạt, khó uống", "drink", -1),
("cafe nhạt, không ngon", "drink", -1),
("smoothie quá nhạt, không hứng thú", "drink", -1),
("nước uống lợ, không ngon", "drink", -1),
("cocktail nhạt, khó uống", "drink", -1),
("matcha latte không đáng tiền", "drink", -1),
("trà sữa pha nhạt, mất vị", "drink", -1),
("cafe pha nhạt, uống khó chịu", "drink", -1),
("smoothie nhạt nhẽo, uống không ngon", "drink", -1),
("nước uống nhạt nhẽo, mất vị", "drink", -1),
("cocktail pha nhạt, khó uống", "drink", -1),
("matcha latte quá nhạt, nhạt vị", "drink", -1),
("trà sữa không ngon, nhạt nhẽo", "drink", -1),
("menu hạn chế, ít lựa chọn", "drink", -1),
("nước uống nhạt, không ngon", "drink", -1),
("đồ ăn không tươi, chất lượng kém", "drink", -1),
("nước lên chậm, tan hết đá trước khi uống", "drink", -1),
("trà sữa nhạt, topping ít và không ngon", "drink", -1),
("cafe pha quá nhạt, mất mùi thơm", "drink", -1),
("cocktail có vị lạ, khó uống", "drink", -1),
("smoothie pha cẩu thả, nhạt và lỏng", "drink", -1),
("matcha latte quá loãng, không béo và nhạt", "drink", -1),
("nước ép hỏng, có mùi khó chịu", "drink", -1),
("trà sữa bị tách lớp, uống không ngon", "drink", -1),
("cafe rang cháy, đắng quá mức", "drink", -1),
("cocktail quá ngọt, mất cân bằng vị", "drink", -1),
("nước lên chậm, tan hết đá trước khi uống", "drink", -1),
("trà sữa nhạt, topping ít và không ngon", "drink", -1),
("cafe pha quá nhạt, mất mùi thơm", "drink", -1),
("cocktail có vị lạ, khó uống", "drink", -1),
("smoothie pha cẩu thả, nhạt và lỏng", "drink", -1),
("matcha latte quá loãng, không béo và nhạt", "drink", -1),
("nước ép hỏng, có mùi khó chịu", "drink", -1),
("trà sữa bị tách lớp, uống không ngon", "drink", -1),
("cafe rang cháy, đắng quá mức", "drink", -1),
("cocktail quá ngọt, mất cân bằng vị", "drink", -1),

# ===================== SERVICE =====================
# ===== Positive =====
("nhân viên cực kỳ nhiệt tình", "service", 1),
("phục vụ nhanh chóng và chuyên nghiệp", "service", 1),
("nhân viên thân thiện và vui vẻ", "service", 1),
("được phục vụ tận tình", "service", 1),
("service rất chu đáo", "service", 1),
("nhân viên hỗ trợ nhanh", "service", 1),
("order nhanh và chính xác", "service", 1),
("nhân viên luôn sẵn sàng giúp đỡ", "service", 1),
("được phục vụ tận tâm", "service", 1),
("nhân viên lịch sự và dễ gần", "service", 1),
("service chất lượng cao", "service", 1),
("phục vụ rất tốt, không phải chờ lâu", "service", 1),
("nhân viên hướng dẫn nhiệt tình", "service", 1),
("phục vụ tận tình và chuyên nghiệp", "service", 1),
("order nhanh gọn, không bị nhầm", "service", 1),
("nhân viên niềm nở và vui vẻ", "service", 1),
("được hỗ trợ đầy đủ khi cần", "service", 1),
("service hoàn hảo, không có gì phải phàn nàn", "service", 1),
("nhân viên thân thiện, tạo cảm giác thoải mái", "service", 1),
("phục vụ rất tận tâm", "service", 1),
("được nhân viên chăm sóc chu đáo", "service", 1),
("order nhanh và phục vụ tốt", "service", 1),
("nhân viên luôn niềm nở", "service", 1),
("service chuyên nghiệp, không gây khó chịu", "service", 1),
("được phục vụ với thái độ tốt", "service", 1),
("nhân viên dễ thương và chu đáo", "service", 1),
("phục vụ nhanh và thân thiện", "service", 1),
("order không mất thời gian", "service", 1),
("nhân viên hỗ trợ khách nhiệt tình", "service", 1),
("được phục vụ tận tình và vui vẻ", "service", 1),
("service hoàn hảo, nhân viên chuyên nghiệp", "service", 1),
("nhân viên dễ gần, hỗ trợ tốt", "service", 1),
("phục vụ chu đáo, không hối hả", "service", 1),
("order nhanh chóng, không lỗi", "service", 1),
("nhân viên luôn niềm nở với khách", "service", 1),
("service chất lượng, tạo ấn tượng tốt", "service", 1),
("được nhân viên hướng dẫn tận tình", "service", 1),
("phục vụ tốt, không bị bỏ quên", "service", 1),
("nhân viên thân thiện, dễ nói chuyện", "service", 1),
("order nhanh, nhân viên hỗ trợ nhiệt tình", "service", 1),
("service hoàn hảo, nhân viên vui vẻ", "service", 1),
("được phục vụ tốt, không phải chờ lâu", "service", 1),
("nhân viên chuyên nghiệp, tạo cảm giác thoải mái", "service", 1),
("phục vụ tận tâm và vui vẻ", "service", 1),
("order nhanh, nhân viên dễ thương", "service", 1),
("nhân viên niềm nở và chu đáo", "service", 1),
("service tốt, nhân viên nhiệt tình", "service", 1),
("được hỗ trợ nhanh chóng khi cần", "service", 1),
("nhân viên dễ gần, phục vụ tốt", "service", 1),
("phục vụ rất tận tâm", "service", 1),
("order nhanh, nhân viên lịch sự", "service", 1),
("nhân viên hỗ trợ khách rất tốt", "service", 1),
("service chuyên nghiệp, không bị chậm", "service", 1),
("được phục vụ chu đáo", "service", 1),
("nhân viên luôn niềm nở, thân thiện", "service", 1),
("phục vụ nhanh chóng, không để khách đợi lâu", "service", 1),
("order chính xác, nhân viên nhiệt tình", "service", 1),
("nhân viên dễ gần, hướng dẫn tận tình", "service", 1),
("service hoàn hảo, nhân viên vui vẻ", "service", 1),
("được phục vụ chu đáo và thân thiện", "service", 1),
("nhân viên lịch sự và nhiệt tình", "service", 1),
("phục vụ nhanh, nhân viên dễ thương", "service", 1),
("order gọn, nhân viên hỗ trợ tốt", "service", 1),
("nhân viên tận tình và niềm nở", "service", 1),
("service chất lượng, nhân viên thân thiện", "service", 1),
("được hỗ trợ đầy đủ", "service", 1),
("nhân viên dễ gần, phục vụ chu đáo", "service", 1),
("phục vụ nhanh, nhân viên niềm nở", "service", 1),
("order chính xác, nhân viên hỗ trợ tốt", "service", 1),
("nhân viên niềm nở, thân thiện", "service", 1),
("service hoàn hảo, không có gì phàn nàn", "service", 1),
("được phục vụ tận tình, nhân viên vui vẻ", "service", 1),
("nhân viên lịch sự, phục vụ nhanh", "service", 1),
("phục vụ tốt, nhân viên thân thiện", "service", 1),
("order nhanh, nhân viên chuyên nghiệp", "service", 1),
("nhân viên niềm nở, hỗ trợ tận tình", "service", 1),
("service chuyên nghiệp, phục vụ chu đáo", "service", 1),
("được phục vụ tốt và nhanh chóng", "service", 1),
("nhân viên tận tâm, dễ gần", "service", 1),
("phục vụ nhanh, nhân viên nhiệt tình", "service", 1),
("order nhanh chóng, nhân viên niềm nở", "service", 1),
("nhân viên thân thiện, phục vụ tốt", "service", 1),
("service hoàn hảo, tạo cảm giác thoải mái", "service", 1),
("được phục vụ chu đáo, nhân viên vui vẻ", "service", 1),
("nhân viên lịch sự, phục vụ tận tâm", "service", 1),
("phục vụ tốt, nhân viên dễ thương", "service", 1),
("order nhanh, nhân viên hỗ trợ tốt", "service", 1),
("nhân viên niềm nở, phục vụ chu đáo", "service", 1),
("service chuyên nghiệp, nhân viên thân thiện", "service", 1),
("được hỗ trợ tận tình", "service", 1),
("nhân viên dễ gần, phục vụ tốt", "service", 1),
("phục vụ nhanh, nhân viên niềm nở", "service", 1),
("order chính xác, nhân viên tận tâm", "service", 1),
("nhân viên thân thiện, phục vụ tốt", "service", 1),
("service hoàn hảo, không có gì phàn nàn", "service", 1),
("được phục vụ chu đáo, nhân viên vui vẻ", "service", 1),
("nhân viên nhiệt tình, phục vụ tốt", "service", 1),
("phục vụ nhanh, nhân viên chuyên nghiệp", "service", 1),
("order gọn, nhân viên hỗ trợ tốt", "service", 1),
("nhân viên niềm nở, phục vụ chu đáo", "service", 1),
("service chất lượng, nhân viên thân thiện", "service", 1),
("được hỗ trợ nhanh chóng", "service", 1),
("nhân viên dễ gần, phục vụ tận tình", "service", 1),
("phục vụ nhanh, nhân viên niềm nở", "service", 1),
("order chính xác, nhân viên hỗ trợ tốt", "service", 1),
("nhân viên thân thiện, phục vụ tốt", "service", 1),
("service hoàn hảo, không có gì phải phàn nàn", "service", 1),
("được phục vụ chu đáo, nhân viên vui vẻ", "service", 1),
("nhân viên lịch sự, phục vụ tốt", "service", 1),
("nhân viên thân thiện, phục vụ nhanh", "service", 1),
("wifi mạnh và ổn định", "service", 1),
("có chỗ gửi xe miễn phí, tiện lợi", "service", 1),
("nhân viên nhiệt tình, dễ thương", "service", 1),
("dịch vụ chu đáo, phục vụ nhanh chóng", "service", 1),
("nhân viên chủ động đề xuất đồ uống phù hợp", "service", 1),
("được phục vụ ngay cả khi quán đông khách", "service", 1),
("phục vụ tận tâm, còn hỗ trợ chỉnh sửa order nhanh chóng", "service", 1),
("nhân viên chủ động gợi ý đồ uống phù hợp", "service", 1),
("được phục vụ ngay cả khi quán đông khách", "service", 1),
("phục vụ tận tâm, hỗ trợ chỉnh sửa order nhanh chóng", "service", 1),
("nhân viên lịch sự, tận tình hướng dẫn menu mới", "service", 1),
("wifi mạnh, ổn định cả ngày", "service", 1),
("có chỗ gửi xe miễn phí, thuận tiện cho khách", "service", 1),
("nhân viên vui vẻ, tạo cảm giác thân thiện ngay từ đầu", "service", 1),
("được phục vụ chu đáo ngay khi vừa đến", "service", 1),
("order nhanh chóng, nhân viên luôn kiểm tra lại để tránh sai sót", "service", 1),
("nhân viên chủ động tư vấn đồ uống phù hợp sở thích", "service", 1),
("phục vụ chuyên nghiệp, không để khách chờ lâu", "service", 1),
("nhân viên dễ thương, tạo không khí thoải mái cho khách", "service", 1),
("dịch vụ nhanh và chính xác, mọi thứ đều hoàn hảo", "service", 1),
("nhân viên nhiệt tình, luôn sẵn sàng giúp khách", "service", 1),
("phục vụ chu đáo, quan tâm từng chi tiết nhỏ", "service", 1),
("order gọn, nhân viên kiểm tra lại giúp khách yên tâm", "service", 1),
("nhân viên niềm nở, khiến khách cảm thấy vui vẻ", "service", 1),
("service chuyên nghiệp, khách không phải lo lắng gì", "service", 1),
("nhân viên hỗ trợ nhanh, không để khách chờ lâu", "service", 1),
("phục vụ tận tâm, còn mang thêm nước khi thấy khách cần", "service", 1),
("nhân viên thân thiện, hướng dẫn tận tình các chương trình khuyến mãi", "service", 1),
("dịch vụ nhanh và hiệu quả, khách cảm thấy thoải mái", "service", 1),
("nhân viên dễ gần, luôn tạo bầu không khí thân thiện", "service", 1),
("phục vụ chuyên nghiệp, mọi yêu cầu đều được đáp ứng", "service", 1),
("nhân viên nhiệt tình, còn gợi ý món mới đáng thử", "service", 1),
("service hoàn hảo, không có gì phàn nàn", "service", 1),
("nhân viên lịch sự, phục vụ nhanh chóng", "service", 1),
("có tiện ích đi kèm tuyệt vời, wifi và chỗ ngồi thoải mái", "service", 1),
("order nhanh chóng, nhân viên còn kiểm tra món trước khi mang ra", "service", 1),
("nhân viên thân thiện, dễ nói chuyện, tạo trải nghiệm tốt", "service", 1),
("phục vụ chu đáo, khách cảm thấy được quan tâm", "service", 1),
("nhân viên luôn niềm nở, hỗ trợ mọi yêu cầu nhanh chóng", "service", 1),
("dịch vụ tận tâm, khiến khách muốn quay lại lần nữa", "service", 1),

# ===== Neutral =====
("phục vụ bình thường", "service", 0),
("nhân viên làm đúng nhiệm vụ", "service", 0),
("service ở mức ổn", "service", 0),
("không có vấn đề gì về phục vụ", "service", 0),
("nhân viên không thân cũng không khó chịu", "service", 0),
("phục vụ đủ dùng", "service", 0),
("phục vụ ổn nhưng hơi chậm", "service", 0),
("nhân viên không quá nổi bật", "service", 0),
("service vừa đủ", "service", 0),
("phục vụ không tốt nhưng cũng không tệ", "service", 0),
("nhân viên làm việc bình thường", "service", 0),
("order ổn, không bị nhầm", "service", 0),
("service đúng tiêu chuẩn", "service", 0),
("nhân viên không niềm nở nhưng cũng không khó chịu", "service", 0),
("phục vụ vừa đủ, không nhanh nhưng cũng không chậm", "service", 0),
("nhân viên làm việc đúng", "service", 0),
("service bình thường, không có gì đặc biệt", "service", 0),
("phục vụ đúng quy trình", "service", 0),
("nhân viên không gây khó chịu", "service", 0),
("order bình thường", "service", 0),
("service vừa tầm, không tốt nhưng không tệ", "service", 0),
("phục vụ không quá nhanh, không quá chậm", "service", 0),
("nhân viên không thân thiện nhưng làm việc đúng", "service", 0),
("service đúng mức", "service", 0),
("phục vụ đúng tiêu chuẩn bình thường", "service", 0),
("nhân viên làm đúng quy trình", "service", 0),
("order ổn, không mất thời gian", "service", 0),
("service vừa phải, không có gì đặc sắc", "service", 0),
("phục vụ đúng cách", "service", 0),
("nhân viên bình thường", "service", 0),
("service không nổi bật, nhưng ổn", "service", 0),
("phục vụ đúng nhưng không thân thiện", "service", 0),
("nhân viên làm việc đúng chức năng", "service", 0),
("order bình thường, không nhanh lắm", "service", 0),
("service tạm ổn", "service", 0),
("phục vụ không tốt cũng không tệ", "service", 0),
("nhân viên làm việc đúng, không niềm nở", "service", 0),
("service vừa đủ, không gây ấn tượng", "service", 0),
("phục vụ theo đúng quy định", "service", 0),
("nhân viên làm công việc bình thường", "service", 0),
("order đúng, không nhanh nhưng cũng không chậm", "service", 0),
("service không nổi bật", "service", 0),
("phục vụ đúng, không có gì để khen hay chê", "service", 0),
("nhân viên làm việc đủ tốt", "service", 0),
("service vừa phải", "service", 0),
("phục vụ bình thường, không để lại ấn tượng", "service", 0),
("nhân viên không gây khó chịu nhưng không nhiệt tình", "service", 0),
("order ổn, đúng yêu cầu", "service", 0),
("service đúng tiêu chuẩn bình thường", "service", 0),
("phục vụ vừa đủ, không quá xuất sắc", "service", 0),
("nhân viên làm việc đúng chức năng", "service", 0),
("service bình thường, không tốt, không xấu", "service", 0),
("phục vụ không quá nhanh cũng không quá chậm", "service", 0),
("nhân viên làm việc vừa đủ", "service", 0),
("order ổn, không gây phiền hà", "service", 0),
("service vừa đủ, không tạo cảm giác đặc biệt", "service", 0),
("phục vụ đúng, không niềm nở nhưng không khó chịu", "service", 0),
("nhân viên làm việc bình thường, đúng yêu cầu", "service", 0),
("service ổn, không có gì để phàn nàn", "service", 0),
("phục vụ vừa đủ, không nổi bật", "service", 0),
("nhân viên làm việc đúng trách nhiệm", "service", 0),
("order bình thường, không có vấn đề gì", "service", 0),
("service tạm ổn, không ấn tượng", "service", 0),
("phục vụ đúng tiêu chuẩn, không nhanh, không chậm", "service", 0),
("nhân viên làm việc đúng, không nổi bật", "service", 0),
("service vừa đủ, không để lại ấn tượng", "service", 0),
("phục vụ ổn, không có gì đặc biệt", "service", 0),
("nhân viên làm việc đúng, không quá nổi bật", "service", 0),
("order ổn, không gây phiền hà", "service", 0),
("service bình thường, đúng yêu cầu", "service", 0),
("phục vụ đúng quy trình, không đặc sắc", "service", 0),
("nhân viên làm việc vừa đủ, không nhiệt tình", "service", 0),
("service tạm ổn, không tốt cũng không xấu", "service", 0),
("phục vụ vừa đủ, không để lại ấn tượng", "service", 0),
("nhân viên làm việc đúng chức năng, bình thường", "service", 0),
("order ổn, phục vụ đúng", "service", 0),
("service vừa đủ, không quá tốt, không quá tệ", "service", 0),
("phục vụ đúng, không để lại ấn tượng", "service", 0),
("nhân viên làm việc bình thường, đúng yêu cầu", "service", 0),
("service bình thường, không nổi bật", "service", 0),
("phục vụ tạm ổn, không gây ấn tượng", "service", 0),
("nhân viên làm việc vừa đủ, không nhiệt tình", "service", 0),
("order đúng, không nhanh nhưng không chậm", "service", 0),
("service tạm ổn, đúng tiêu chuẩn", "service", 0),
("phục vụ bình thường, không để lại ấn tượng", "service", 0),
("nhân viên làm việc đúng, không nổi bật", "service", 0),
("dịch vụ bình thường, không có gì đặc biệt", "service", 0),
("wifi có lúc chậm, có lúc ổn định", "service", 0),
("gửi xe vừa đủ, không tốt cũng không tệ", "service", 0),
("nhân viên lịch sự nhưng không quá nhiệt tình", "service", 0),
("phục vụ vừa đủ, nhưng khách phải đợi lâu hơn bình thường", "service", 0),
("nhân viên làm đúng nhưng không thân thiện, không nổi bật", "service", 0),
("wifi đôi lúc chập chờn, không ảnh hưởng quá nhiều", "service", 0),
("gửi xe tạm ổn, hơi chật vào giờ cao điểm", "service", 0),
("phục vụ bình thường, không nhanh cũng không chậm", "service", 0),
("nhân viên làm đúng nhiệm vụ, không nổi bật", "service", 0),
("service vừa đủ, khách không cảm thấy ấn tượng", "service", 0),
("order ổn, không nhầm nhưng cũng không nhanh", "service", 0),
("nhân viên không quá niềm nở nhưng không khó chịu", "service", 0),
("phục vụ tạm ổn, đôi khi khách phải chờ", "service", 0),
("wifi ổn, đôi lúc hơi chậm vào giờ cao điểm", "service", 0),
("gửi xe vừa đủ, không quá tiện nhưng cũng không khó", "service", 0),
("nhân viên làm việc đúng chức năng, không thân thiện lắm", "service", 0),
("service đúng tiêu chuẩn, không đặc sắc", "service", 0),
("phục vụ vừa đủ, order không bị nhầm", "service", 0),
("nhân viên làm việc bình thường, không để lại ấn tượng", "service", 0),
("service ổn, khách không hài lòng nhưng cũng không thất vọng", "service", 0),
("order bình thường, nhân viên kiểm tra đơn vừa đủ", "service", 0),
("phục vụ không nhanh, nhưng không quá chậm", "service", 0),
("nhân viên làm đúng, không thân thiện, không khó chịu", "service", 0),
("service vừa đủ, khách không ấn tượng lắm", "service", 0),
("phục vụ đúng quy trình, không có gì nổi bật", "service", 0),
("nhân viên làm việc vừa đủ, không quá nhiệt tình", "service", 0),
("wifi có lúc chậm, có lúc ổn định", "service", 0),
("gửi xe tạm ổn, giờ cao điểm hơi chật", "service", 0),
("service bình thường, không nổi bật nhưng đủ dùng", "service", 0),
("nhân viên làm việc bình thường, đúng yêu cầu", "service", 0),
("phục vụ đúng, không để lại ấn tượng đặc biệt", "service", 0),
("order bình thường, không nhầm nhưng hơi chậm", "service", 0),
("service tạm ổn, không tốt, không xấu", "service", 0),
("nhân viên không gây khó chịu nhưng cũng không niềm nở", "service", 0),
("phục vụ vừa đủ, không nổi bật, khách không phàn nàn", "service", 0),
("order ổn, phục vụ đúng nhưng không nhanh", "service", 0),
("nhân viên làm việc bình thường, không tạo cảm giác thân thiện", "service", 0),
("service đúng mức, không để lại ấn tượng tốt hay xấu", "service", 0),
("phục vụ đúng cách, không tốt cũng không tệ", "service", 0),
("nhân viên làm việc vừa đủ, không nổi bật", "service", 0),

# ===== Negative =====
("nhân viên thái độ kém", "service", -1),
("phục vụ rất chậm", "service", -1),
("bị lơ khách", "service", -1),
("nhân viên khó chịu", "service", -1),
("service quá tệ", "service", -1),
("gọi mãi không ai ra", "service", -1),
("phục vụ thiếu chuyên nghiệp", "service", -1),
("nhân viên cáu gắt", "service", -1),
("nhân viên nhiệt tình nhưng phục vụ chậm", "service", -1),
("phục vụ lơ là, không quan tâm khách", "service", -1),
("nhân viên hời hợt", "service", -1),
("service không chuyên nghiệp", "service", -1),
("phục vụ rất chậm, khách phải đợi lâu", "service", -1),
("nhân viên thiếu lịch sự", "service", -1),
("bị nhân viên bỏ qua", "service", -1),
("service không tận tâm", "service", -1),
("phục vụ cẩu thả", "service", -1),
("nhân viên làm việc không tập trung", "service", -1),
("order bị nhầm, phục vụ chậm", "service", -1),
("service quá kém", "service", -1),
("nhân viên thờ ơ", "service", -1),
("phục vụ không quan tâm khách", "service", -1),
("nhân viên thiếu nhiệt tình", "service", -1),
("service làm khách khó chịu", "service", -1),
("phục vụ chậm và không tận tâm", "service", -1),
("nhân viên cau có", "service", -1),
("order sai, phục vụ lơ là", "service", -1),
("service quá tệ, không hài lòng", "service", -1),
("nhân viên khó chịu, thái độ xấu", "service", -1),
("phục vụ chậm, thiếu chu đáo", "service", -1),
("nhân viên không thân thiện", "service", -1),
("service khiến khách bực mình", "service", -1),
("phục vụ kém, khách phải chờ lâu", "service", -1),
("nhân viên thờ ơ, không quan tâm", "service", -1),
("service không đạt tiêu chuẩn", "service", -1),
("phục vụ quá chậm, khách phàn nàn", "service", -1),
("nhân viên hời hợt, thái độ không tốt", "service", -1),
("order nhầm, nhân viên không sửa kịp", "service", -1),
("service quá kém, không chuyên nghiệp", "service", -1),
("nhân viên khó chịu, phục vụ tệ", "service", -1),
("phục vụ chậm và thiếu thân thiện", "service", -1),
("nhân viên cáu gắt, phục vụ không tốt", "service", -1),
("service làm khách khó chịu, không hài lòng", "service", -1),
("phục vụ thiếu chuyên nghiệp, order bị nhầm", "service", -1),
("nhân viên thờ ơ, phục vụ chậm", "service", -1),
("service quá tệ, nhân viên không niềm nở", "service", -1),
("phục vụ lơ là, không chu đáo", "service", -1),
("nhân viên cau có, không quan tâm khách", "service", -1),
("order sai, phục vụ tệ", "service", -1),
("service làm khách khó chịu, thái độ nhân viên xấu", "service", -1),
("phục vụ chậm, nhân viên không nhiệt tình", "service", -1),
("nhân viên hời hợt, phục vụ kém", "service", -1),
("service tệ, không đáng tiền", "service", -1),
("phục vụ thiếu chu đáo, nhân viên thái độ xấu", "service", -1),
("nhân viên cau có, phục vụ chậm", "service", -1),
("order sai, không được phục vụ tốt", "service", -1),
("service khiến khách phiền lòng", "service", -1),
("phục vụ kém, không chuyên nghiệp", "service", -1),
("nhân viên không niềm nở, thái độ xấu", "service", -1),
("service quá tệ, khiến khách thất vọng", "service", -1),
("phục vụ chậm và lơ là", "service", -1),
("nhân viên khó chịu, không chu đáo", "service", -1),
("order nhầm, nhân viên thờ ơ", "service", -1),
("service không chuyên nghiệp, thái độ kém", "service", -1),
("phục vụ tệ, nhân viên cau có", "service", -1),
("nhân viên thờ ơ, phục vụ không tận tình", "service", -1),
("service làm khách thất vọng", "service", -1),
("phục vụ chậm, nhân viên không niềm nở", "service", -1),
("nhân viên cau có, phục vụ tệ", "service", -1),
("service quá kém, khách không hài lòng", "service", -1),
("phục vụ không chuyên nghiệp, thái độ nhân viên tệ", "service", -1),
("nhân viên khó chịu, phục vụ không tốt", "service", -1),
("service khiến khách phiền lòng và khó chịu", "service", -1),
("phục vụ chậm, nhân viên hời hợt", "service", -1),
("nhân viên thờ ơ, không quan tâm khách", "service", -1),
("service tệ, nhân viên không chu đáo", "service", -1),
("phục vụ thiếu chuyên nghiệp, order bị nhầm", "service", -1),
("nhân viên thái độ xấu, phục vụ tệ", "service", -1),
("service làm khách thất vọng, không hài lòng", "service", -1),
("phục vụ chậm, nhân viên không nhiệt tình", "service", -1),
("nhân viên cau có, phục vụ kém", "service", -1),
("service tệ, khiến khách bực mình", "service", -1),
("phục vụ kém, nhân viên thái độ xấu", "service", -1),
("nhân viên thờ ơ, phục vụ chậm", "service", -1),
("service quá tệ, không đáp ứng yêu cầu khách", "service", -1),
("wifi yếu, khó kết nối", "service", -1),
("gửi xe bất tiện, chật chội", "service", -1),
("nhân viên phục vụ chậm, thiếu nhiệt tình", "service", -1),
("nhân viên thờ ơ, phục vụ chậm, wifi yếu", "service", -1),
("order nhầm, nhân viên cáu gắt, khách phải chờ lâu", "service", -1),
("gửi xe khó khăn, nhân viên không hỗ trợ, thái độ kém", "service", -1),
("service chậm, nhân viên hời hợt, không đáp ứng yêu cầu khách", "service", -1),
("nhân viên thái độ xấu, phục vụ chậm", "service", -1),
("phục vụ rất chậm, khách phải đợi lâu", "service", -1),
("bị lơ khách, nhân viên không quan tâm", "service", -1),
("nhân viên khó chịu, phục vụ không chu đáo", "service", -1),
("service quá tệ, khiến khách thất vọng", "service", -1),
("gọi mãi không ai ra, phải tự nhắc", "service", -1),
("phục vụ thiếu chuyên nghiệp, order nhầm", "service", -1),
("nhân viên cáu gắt khi khách hỏi thêm", "service", -1),
("phục vụ chậm và thiếu thân thiện", "service", -1),
("service không tận tâm, khiến khách bực mình", "service", -1),
("nhân viên thờ ơ, không quan tâm khách", "service", -1),
("order sai, nhân viên không sửa kịp", "service", -1),
("nhân viên hời hợt, thái độ xấu", "service", -1),
("phục vụ lơ là, không chu đáo", "service", -1),
("service tệ, khách phải chờ lâu, không hài lòng", "service", -1),
("nhân viên cau có, phục vụ chậm", "service", -1),
("phục vụ kém, khách phải nhắc nhiều lần", "service", -1),
("order nhầm, nhân viên thờ ơ", "service", -1),
("service không chuyên nghiệp, thái độ kém", "service", -1),
("nhân viên khó chịu, không niềm nở", "service", -1),
("phục vụ quá chậm, khách phàn nàn", "service", -1),
("nhân viên thờ ơ, phục vụ chậm và lơ là", "service", -1),
("service khiến khách phiền lòng và khó chịu", "service", -1),
("nhân viên cau có, không quan tâm khách", "service", -1),
("phục vụ chậm, order bị nhầm, thái độ xấu", "service", -1),
("nhân viên không thân thiện, phục vụ kém", "service", -1),
("service tệ, khách không hài lòng, không đáng tiền", "service", -1),
("phục vụ thiếu chu đáo, order nhầm", "service", -1),
("nhân viên thái độ kém, phục vụ chậm", "service", -1),
("service quá tệ, khiến khách thất vọng", "service", -1),
("wifi yếu, khó kết nối, ảnh hưởng trải nghiệm", "service", -1),
("gửi xe bất tiện, chật chội, nhân viên không hỗ trợ", "service", -1),
("nhân viên phục vụ chậm, thiếu nhiệt tình, thái độ kém", "service", -1),

# ===================== PRICE =====================
# ===== Positive =====
("giá hợp lý", "price", 1),
("giá rẻ", "price", 1),
("mức giá dễ chịu", "price", 1),
("giá xứng đáng với chất lượng", "price", 1),
("giá ok", "price", 1),
("mức giá tốt", "price", 1),
("giá cả phải chăng", "price", 1),
("không mắc, hợp lý", "price", 1),
("giá vừa túi tiền", "price", 1),
("giá ổn so với chất lượng", "price", 1),
("rất đáng tiền", "price", 1),
("giá hợp lý cho đồ uống", "price", 1),
("mức giá dễ chịu cho mọi người", "price", 1),
("giá không quá cao", "price", 1),
("giá tốt so với chất lượng", "price", 1),
("uống vừa túi tiền", "price", 1),
("giá hợp lý, không chặt khách", "price", 1),
("giá phải chăng", "price", 1),
("giá tốt cho chất lượng nhận được", "price", 1),
("mức giá vừa phải", "price", 1),
("giá hợp lý và đáng tiền", "price", 1),
("giá vừa phải cho mọi loại đồ uống", "price", 1),
("rẻ so với chất lượng", "price", 1),
("mức giá dễ chịu, không quá đắt", "price", 1),
("giá ok, không quá cao", "price", 1),
("giá hợp lý, vừa túi tiền sinh viên", "price", 1),
("giá cả phải chăng cho một quán đẹp", "price", 1),
("mức giá dễ chịu, hợp lý", "price", 1),
("giá ok, đáng đồng tiền", "price", 1),
("giá hợp lý cho đồ uống chất lượng", "price", 1),
("giá ổn, không mắc", "price", 1),
("rẻ và ngon", "price", 1),
("giá tốt, đáng thử", "price", 1),
("giá hợp lý, phù hợp với mọi người", "price", 1),
("mức giá dễ chịu, đáng tiền", "price", 1),
("giá không quá mắc, chất lượng tốt", "price", 1),
("giá hợp lý, phù hợp với học sinh sinh viên", "price", 1),
("giá vừa phải, chất lượng tương xứng", "price", 1),
("mức giá tốt, không quá đắt", "price", 1),
("giá hợp lý, khách không phàn nàn", "price", 1),
("giá ok, vừa túi tiền", "price", 1),
("giá hợp lý, đáng đồng tiền bát gạo", "price", 1),
("giá ổn, hợp lý cho đồ uống", "price", 1),
("giá tốt, không bị chặt chém", "price", 1),
("giá phải chăng, chất lượng tương xứng", "price", 1),
("giá hợp lý, không quá mắc", "price", 1),
("mức giá vừa phải, đáng tiền", "price", 1),
("giá ổn, chất lượng tốt", "price", 1),
("giá hợp lý, không gây khó chịu", "price", 1),
("giá tốt, phù hợp với chất lượng", "price", 1),
("giá hợp lý, vừa phải", "price", 1),
("mức giá tốt, đáng đồng tiền", "price", 1),
("giá ok, hợp lý", "price", 1),
("giá hợp lý, vừa túi tiền khách", "price", 1),
("giá tốt, xứng đáng với chất lượng", "price", 1),
("giá hợp lý, đồ uống ngon", "price", 1),
("giá vừa phải, đáng tiền", "price", 1),
("giá tốt, không đắt đỏ", "price", 1),
("giá hợp lý, vừa túi tiền sinh viên", "price", 1),
("mức giá dễ chịu, hợp lý cho mọi người", "price", 1),
("giá ok, đáng tiền", "price", 1),
("giá hợp lý, không chặt khách", "price", 1),
("giá tốt, đồ uống ngon", "price", 1),
("giá hợp lý, xứng đáng với đồ uống", "price", 1),
("giá ổn, phù hợp với chất lượng", "price", 1),
("giá phải chăng, đáng tiền", "price", 1),
("giá hợp lý, không quá mắc", "price", 1),
("giá ok, chất lượng tốt", "price", 1),
("mức giá vừa phải, hợp lý", "price", 1),
("giá hợp lý, xứng đáng với số tiền bỏ ra", "price", 1),
("giá tốt, không mắc", "price", 1),
("giá hợp lý, đồ uống ngon, vừa túi tiền", "price", 1),
("giá ổn, hợp lý", "price", 1),
("giá phải chăng, chất lượng tương xứng", "price", 1),
("giá hợp lý, đáng đồng tiền", "price", 1),
("giá tốt, hợp lý", "price", 1),
("giá hợp lý, vừa túi tiền khách", "price", 1),
("giá ổn, hợp lý với chất lượng", "price", 1),
("giá hợp lý, đáng tiền", "price", 1),
("giá tốt, đồ uống xứng đáng", "price", 1),
("giá hợp lý, mức giá vừa phải", "price", 1),
("giá ok, hợp lý và đáng tiền", "price", 1),
("giá hợp lý, chất lượng tốt", "price", 1),
("giá ổn, phù hợp với chất lượng", "price", 1),
("giá hợp lý, đồ uống ngon và rẻ", "price", 1),
("giá tốt, đáng đồng tiền", "price", 1),
("giá hợp lý, không quá đắt", "price", 1),
("giá ok, hợp lý, vừa túi tiền", "price", 1),
("giá hợp lý, xứng đáng với chất lượng", "price", 1),
("giá ổn, đồ uống ngon", "price", 1),
("giá phải chăng, chất lượng tương xứng", "price", 1),
("giá hợp lý, vừa túi tiền, đáng đồng tiền", "price", 1),
("giá quá hợp lý cho chất lượng nhận được", "price", 1),
("mức giá rẻ nhưng chất lượng tốt", "price", 1),
("giá cả rất vừa túi tiền", "price", 1),
("giá hợp lý, xứng đáng trải nghiệm", "price", 1),
("mức giá tốt, hợp lý cho mọi khách hàng", "price", 1),
("giá rẻ mà chất lượng đồ uống ngon", "price", 1),
("giá phù hợp với sinh viên", "price", 1),
("giá phải chăng, đáng tiền", "price", 1),
("giá ok, phù hợp chất lượng", "price", 1),
("giá hợp lý, không lo chặt chém", "price", 1),
("giá ổn, đáng thử", "price", 1),
("mức giá hợp lý, đồ uống ngon", "price", 1),
("giá vừa phải, xứng đáng đồng tiền", "price", 1),
("giá hợp lý, dễ chịu cho ví tiền", "price", 1),
("giá tốt, hợp lý với dịch vụ", "price", 1),
("giá vừa túi tiền, chất lượng ngon", "price", 1),
("giá rẻ, đáng trải nghiệm", "price", 1),
("giá hợp lý, vừa phải cho mọi loại đồ uống", "price", 1),
("giá tốt, đáng đồng tiền bát gạo", "price", 1),
("giá ok, không quá mắc", "price", 1),
("mức giá hợp lý, không đắt", "price", 1),
("giá hợp lý cho đồ uống chất lượng cao", "price", 1),
("giá rẻ, chất lượng tốt", "price", 1),
("giá hợp lý, không bị chặt chém", "price", 1),
("giá vừa phải, đáng đồng tiền", "price", 1),
("giá ổn, phù hợp mọi đối tượng", "price", 1),
("giá tốt, chất lượng xứng đáng", "price", 1),
("giá hợp lý, đồ uống ngon và rẻ", "price", 1),
("giá phải chăng, phù hợp học sinh sinh viên", "price", 1),
("giá hợp lý, không làm khách khó chịu", "price", 1),
("giá ok, đồ uống đáng thử", "price", 1),
("giá ổn, vừa túi tiền sinh viên", "price", 1),
("giá hợp lý, đồ uống chất lượng cao", "price", 1),
("giá rẻ, đồ uống ngon", "price", 1),
("giá hợp lý, đáng trải nghiệm thử", "price", 1),
("giá vừa túi tiền, chất lượng xứng đáng", "price", 1),
("giá hợp lý, đáng đồng tiền bỏ ra", "price", 1),
("giá tốt, hợp lý cho mọi loại đồ uống", "price", 1),
("giá ổn, chất lượng tương xứng", "price", 1),
("giá vừa phải, hợp lý với chất lượng", "price", 1),
("giá hợp lý, không quá mắc, ngon", "price", 1),
("giá ok, đáng đồng tiền", "price", 1),
("giá hợp lý, vừa túi tiền khách hàng", "price", 1),
("giá ổn, xứng đáng thử", "price", 1),
("giá hợp lý, chất lượng tốt, đáng tiền", "price", 1),
("giá phải chăng, đồ uống ngon", "price", 1),
("giá rẻ, đồ uống ngon, hợp lý", "price", 1),
("giá ok, phù hợp chất lượng nhận được", "price", 1),
("giá hợp lý, dễ chịu, vừa túi tiền", "price", 1),
("giá tốt, đáng thử và hợp lý", "price", 1),
("giá hợp lý, vừa phải cho chất lượng đồ uống", "price", 1),
("giá ok, phù hợp mọi người", "price", 1),

# ===== Neutral =====
("giá bình thường", "price", 0),
("không rẻ cũng không mắc", "price", 0),
("giá theo mặt bằng chung", "price", 0),
("mức giá quen thuộc", "price", 0),
("giá không thay đổi nhiều", "price", 0),
("không mắc cũng không rẻ", "price", 0),
("giá vừa tầm", "price", 0),
("mức giá trung bình", "price", 0),
("giá không cao, không thấp", "price", 0),
("giá ổn định", "price", 0),
("giá tạm được", "price", 0),
("không mắc, không rẻ", "price", 0),
("giá ở mức trung bình", "price", 0),
("mức giá bình thường", "price", 0),
("giá vừa phải, không tốt, không tệ", "price", 0),
("giá như mọi quán khác", "price", 0),
("giá không có gì đặc biệt", "price", 0),
("mức giá bình thường so với thị trường", "price", 0),
("giá vừa phải, không quá ấn tượng", "price", 0),
("giá ở mức tạm ổn", "price", 0),
("giá vừa phải, không quá cao", "price", 0),
("giá ổn, vừa phải", "price", 0),
("mức giá bình thường, hợp lý", "price", 0),
("giá không quá chát", "price", 0),
("giá vừa tầm, không rẻ cũng không mắc", "price", 0),
("mức giá vừa phải, tạm ổn", "price", 0),
("giá vừa phải, trung bình", "price", 0),
("giá ổn, không gây khó chịu", "price", 0),
("giá không quá rẻ, không quá mắc", "price", 0),
("giá tạm ổn", "price", 0),
("giá trung bình, không đặc sắc", "price", 0),
("giá vừa phải, không rẻ cũng không mắc", "price", 0),
("giá bình thường, không quá cao", "price", 0),
("giá vừa tầm, hợp lý", "price", 0),
("giá trung bình, ổn", "price", 0),
("giá vừa phải, không ấn tượng", "price", 0),
("giá không quá cao, vừa tầm", "price", 0),
("mức giá bình thường, không gây khó chịu", "price", 0),
("giá ổn, không quá đắt", "price", 0),
("giá trung bình, tạm ổn", "price", 0),
("giá vừa phải, không đặc sắc", "price", 0),
("giá bình thường, hợp lý", "price", 0),
("giá vừa tầm, mức giá trung bình", "price", 0),
("giá ổn, không quá cao cũng không quá thấp", "price", 0),
("giá bình thường, hợp lý cho mọi người", "price", 0),
("giá trung bình, không quá ấn tượng", "price", 0),
("giá vừa phải, mức giá trung bình", "price", 0),
("giá bình thường, không mắc, không rẻ", "price", 0),
("giá tạm ổn, không quá cao", "price", 0),
("giá ổn, mức giá vừa phải", "price", 0),
("giá bình thường, hợp lý với chất lượng", "price", 0),
("giá vừa tầm, tạm ổn", "price", 0),
("giá trung bình, không đặc sắc", "price", 0),
("giá ổn, mức giá trung bình", "price", 0),
("giá vừa phải, hợp lý", "price", 0),
("giá bình thường, không ấn tượng", "price", 0),
("giá ổn, vừa tầm", "price", 0),
("giá trung bình, tạm ổn", "price", 0),
("giá vừa phải, không quá cao", "price", 0),
("giá bình thường, vừa phải", "price", 0),
("giá ổn, mức giá trung bình", "price", 0),
("giá vừa tầm, không quá mắc", "price", 0),
("giá bình thường, mức giá tạm ổn", "price", 0),
("giá trung bình, hợp lý", "price", 0),
("giá ổn, không gây khó chịu", "price", 0),
("giá vừa phải, trung bình", "price", 0),
("giá bình thường, tạm ổn", "price", 0),
("giá ổn, vừa tầm", "price", 0),
("giá trung bình, hợp lý cho mọi người", "price", 0),
("giá bình thường, không quá cao", "price", 0),
("giá ổn, mức giá vừa tầm", "price", 0),
("giá vừa phải, không quá ấn tượng", "price", 0),
("giá bình thường, tạm ổn", "price", 0),
("giá ổn, mức giá trung bình", "price", 0),
("giá vừa phải, hợp lý với chất lượng", "price", 0),
("giá bình thường, không quá cao", "price", 0),
("giá ổn, mức giá vừa phải", "price", 0),
("giá vừa tầm, tạm ổn", "price", 0),
("giá bình thường, mức giá trung bình", "price", 0),
("giá ổn, mức giá vừa tầm", "price", 0),
("giá vừa phải, trung bình", "price", 0),
("giá bình thường, hợp lý", "price", 0),
("giá ổn, vừa tầm", "price", 0),
("giá trung bình, mức giá tạm ổn", "price", 0),
("giá vừa phải, tạm ổn", "price", 0),
("giá bình thường, không quá cao", "price", 0),
("giá ổn, mức giá trung bình", "price", 0),
("giá vừa tầm, hợp lý", "price", 0),
("giá bình thường, tạm ổn", "price", 0),
("giá ổn, vừa tầm", "price", 0),
("giá trung bình, mức giá hợp lý", "price", 0),
("giá vừa phải, không quá mắc", "price", 0),
("giá bình thường, tạm ổn", "price", 0),
("giá ổn, mức giá trung bình", "price", 0),
("giá bình thường, không quá rẻ cũng không quá mắc", "price", 0),
("giá tạm ổn", "price", 0),
("giá vừa phải, mức trung bình", "price", 0),
("giá theo mặt bằng chung", "price", 0),
("mức giá không thay đổi nhiều", "price", 0),
("giá vừa tầm, không cao cũng không thấp", "price", 0),
("giá trung bình, hợp lý", "price", 0),
("giá ổn, không gây khó chịu", "price", 0),
("giá vừa phải, không đặc sắc", "price", 0),
("giá bình thường, mức tạm ổn", "price", 0),
("giá không quá cao, vừa tầm", "price", 0),
("mức giá trung bình, không đặc sắc", "price", 0),
("giá ổn, vừa tầm với chất lượng", "price", 0),
("giá bình thường, tạm ổn cho mọi người", "price", 0),
("giá vừa phải, không rẻ cũng không mắc", "price", 0),
("giá bình thường, không đặc sắc", "price", 0),
("giá tạm ổn, mức trung bình", "price", 0),
("giá vừa tầm, mức giá trung bình", "price", 0),
("giá ổn, mức giá vừa phải", "price", 0),
("giá vừa phải, hợp lý với chất lượng", "price", 0),
("giá bình thường, mức tạm ổn", "price", 0),
("giá trung bình, hợp lý cho mọi người", "price", 0),
("giá ổn, vừa tầm, không quá cao", "price", 0),
("giá bình thường, mức giá trung bình", "price", 0),
("giá tạm ổn, không đặc sắc", "price", 0),
("giá vừa phải, tạm ổn", "price", 0),
("giá bình thường, hợp lý với mọi đối tượng", "price", 0),
("giá ổn, mức trung bình", "price", 0),
("giá vừa tầm, mức giá hợp lý", "price", 0),
("giá bình thường, tạm ổn, không quá đắt", "price", 0),
("giá vừa phải, trung bình", "price", 0),
("giá ổn, mức giá vừa tầm", "price", 0),
("giá bình thường, không gây khó chịu", "price", 0),
("giá vừa phải, mức giá trung bình", "price", 0),
("giá ổn, không quá cao", "price", 0),
("giá bình thường, tạm ổn", "price", 0),
("giá vừa tầm, không quá ấn tượng", "price", 0),
("giá trung bình, mức giá tạm ổn", "price", 0),
("giá vừa phải, hợp lý với chất lượng", "price", 0),
("giá ổn, mức giá vừa tầm", "price", 0),
("giá bình thường, tạm ổn cho mọi người", "price", 0),
("giá vừa tầm, mức giá trung bình", "price", 0),
("giá ổn, vừa tầm với chất lượng", "price", 0),
("giá vừa phải, mức trung bình", "price", 0),
("giá bình thường, hợp lý với chất lượng", "price", 0),
("giá tạm ổn, mức giá vừa phải", "price", 0),
("giá vừa tầm, không quá cao", "price", 0),
("giá ổn, không quá đắt cũng không quá rẻ", "price", 0),

# ===== Negative =====
("giá quá cao", "price", -1),
("mắc so với chất lượng", "price", -1),
("giá không xứng đáng", "price", -1),
("uống mà thấy xót tiền", "price", -1),
("giá chát", "price", -1),
("giá cao vô lý", "price", -1),
("mức giá đắt quá", "price", -1),
("giá không hợp lý", "price", -1),
("phải trả nhiều nhưng không ngon", "price", -1),
("giá cao mà chất lượng bình thường", "price", -1),
("giá vượt quá kỳ vọng", "price", -1),
("quá mắc so với dịch vụ", "price", -1),
("giá đắt đỏ", "price", -1),
("giá cao hơn mặt bằng chung", "price", -1),
("giá quá chát so với đồ uống", "price", -1),
("giá không đáng tiền", "price", -1),
("giá cao nhưng không ngon", "price", -1),
("phải trả quá nhiều cho đồ uống", "price", -1),
("giá quá mức", "price", -1),
("giá quá cao, không hợp lý", "price", -1),
("uống một lần mà tiếc tiền", "price", -1),
("giá đắt hơn các quán khác", "price", -1),
("giá không xứng với chất lượng", "price", -1),
("giá cao, mức chi trả quá lớn", "price", -1),
("giá quá chát cho đồ uống này", "price", -1),
("mức giá không hợp lý", "price", -1),
("giá quá đắt đỏ", "price", -1),
("giá cao, không tương xứng", "price", -1),
("giá cao quá, không đáng tiền", "price", -1),
("uống mà thấy mắc quá", "price", -1),
("giá cao hơn mong đợi", "price", -1),
("giá đắt, không xứng đáng", "price", -1),
("giá chát so với chất lượng", "price", -1),
("giá quá đắt", "price", -1),
("giá không hợp lý cho túi tiền", "price", -1),
("giá quá cao so với dịch vụ", "price", -1),
("phải trả quá nhiều cho mức này", "price", -1),
("giá cao, không đáng đồng tiền", "price", -1),
("giá quá mắc so với chất lượng", "price", -1),
("giá chát, không xứng đáng", "price", -1),
("giá quá cao, đồ uống bình thường", "price", -1),
("giá cao, không hợp lý cho khách", "price", -1),
("giá đắt, không xứng với dịch vụ", "price", -1),
("giá cao quá, không đáng thử", "price", -1),
("giá quá đắt, không hợp lý", "price", -1),
("giá cao mà đồ uống bình thường", "price", -1),
("giá không hợp lý, quá chát", "price", -1),
("giá cao, khách sẽ ngại thử", "price", -1),
("giá đắt, không xứng đáng trải nghiệm", "price", -1),
("giá quá chát so với chất lượng đồ uống", "price", -1),
("giá cao, không hợp lý cho túi tiền", "price", -1),
("giá quá mắc, đồ uống bình thường", "price", -1),
("giá cao hơn mong muốn", "price", -1),
("giá chát, không đáng tiền", "price", -1),
("giá quá đắt, không nên thử", "price", -1),
("giá cao, không hợp lý", "price", -1),
("giá cao so với chất lượng", "price", -1),
("giá quá cao, không hợp lý", "price", -1),
("mắc so với chất lượng", "price", -1),
("giá không xứng đáng", "price", -1),
("uống mà thấy xót tiền", "price", -1),
("giá chát, không đáng tiền", "price", -1),
("giá cao vô lý", "price", -1),
("mức giá đắt quá, không hợp lý", "price", -1),
("phải trả nhiều nhưng chất lượng bình thường", "price", -1),
("giá cao mà đồ uống không ngon", "price", -1),
("giá vượt quá kỳ vọng", "price", -1),
("quá mắc so với dịch vụ", "price", -1),
("giá đắt đỏ, không xứng", "price", -1),
("giá cao hơn mặt bằng chung", "price", -1),
("giá không đáng tiền bỏ ra", "price", -1),
("giá cao mà không ngon", "price", -1),
("phải trả quá nhiều cho đồ uống này", "price", -1),
("giá quá mức, không hợp lý", "price", -1),
("giá cao, không xứng đáng", "price", -1),
("uống một lần mà tiếc tiền", "price", -1),
("giá đắt hơn các quán khác", "price", -1),
("giá không xứng với chất lượng", "price", -1),
("giá cao, mức chi trả quá lớn", "price", -1),
("giá quá chát cho đồ uống này", "price", -1),
("giá không hợp lý cho túi tiền", "price", -1),
("giá quá cao so với dịch vụ", "price", -1),
("phải trả quá nhiều cho mức này", "price", -1),
("giá cao, không đáng đồng tiền", "price", -1),
("giá quá mắc so với chất lượng", "price", -1),
("giá chát, không xứng đáng", "price", -1),
("giá quá cao, đồ uống bình thường", "price", -1),
("giá cao, không hợp lý cho khách", "price", -1),
("giá đắt, không xứng với dịch vụ", "price", -1),
("giá cao quá, không đáng thử", "price", -1),
("giá quá đắt, không hợp lý", "price", -1),
("giá cao mà đồ uống bình thường", "price", -1),
("giá không hợp lý, quá chát", "price", -1),
("giá cao, khách sẽ ngại thử", "price", -1),
("giá đắt, không xứng đáng trải nghiệm", "price", -1),
("giá quá chát so với chất lượng đồ uống", "price", -1),
("giá cao, không hợp lý cho túi tiền", "price", -1),
("giá quá mắc, đồ uống bình thường", "price", -1),
("giá cao hơn mong muốn", "price", -1),
("giá chát, không đáng tiền", "price", -1),
("giá quá đắt, không nên thử", "price", -1),
("giá cao, không hợp lý", "price", -1),
("giá cao so với chất lượng", "price", -1),

# ===================== AMBIANCE =====================
# ===== Positive =====
("không gian rất đẹp", "ambiance", 1),
("quán trang trí xinh xắn", "ambiance", 1),
("ngồi thoải mái, rộng rãi", "ambiance", 1),
("view đẹp, hợp chụp ảnh", "ambiance", 1),
("decor hiện đại, dễ chịu", "ambiance", 1),
("quán nhìn rất chill", "ambiance", 1),
("không gian sáng sủa, thoáng", "ambiance", 1),
("ngồi lâu cũng không mỏi", "ambiance", 1),
("view nhìn ra sông đẹp", "ambiance", 1),
("quán ấm cúng, dễ chịu", "ambiance", 1),
("decor tinh tế, sang trọng", "ambiance", 1),
("không gian rộng rãi, thoáng mát", "ambiance", 1),
("ngồi rất dễ chịu, thoải mái", "ambiance", 1),
("quán trang trí đẹp, hợp trend", "ambiance", 1),
("view quán rất xinh", "ambiance", 1),
("decor nhẹ nhàng, dễ chịu", "ambiance", 1),
("không gian yên tĩnh, thư giãn", "ambiance", 1),
("ngồi uống trà rất thoải mái", "ambiance", 1),
("view quán chill, hợp sống ảo", "ambiance", 1),
("quán rộng, có nhiều ánh sáng", "ambiance", 1),
("decor bắt mắt, dễ chịu", "ambiance", 1),
("không gian trong lành, thoáng mát", "ambiance", 1),
("ngồi lâu không thấy mệt", "ambiance", 1),
("quán có nhiều cây xanh, view đẹp", "ambiance", 1),
("decor đẹp, sang trọng", "ambiance", 1),
("view mở, không gian thoáng", "ambiance", 1),
("quán trang trí hợp mắt, dễ chịu", "ambiance", 1),
("không gian sạch sẽ, gọn gàng", "ambiance", 1),
("ngồi vừa thoải mái vừa yên tĩnh", "ambiance", 1),
("decor hài hòa, đẹp mắt", "ambiance", 1),
("view xịn, quán rộng rãi", "ambiance", 1),
("quán dễ chịu, không gian thoáng", "ambiance", 1),
("không gian đẹp, thư giãn", "ambiance", 1),
("decor tinh tế, thoải mái", "ambiance", 1),
("ngồi uống cà phê rất dễ chịu", "ambiance", 1),
("view đẹp, ánh sáng tốt", "ambiance", 1),
("quán ấm áp, trang trí đẹp", "ambiance", 1),
("không gian yên tĩnh, dễ chịu", "ambiance", 1),
("ngồi lâu mà vẫn thoải mái", "ambiance", 1),
("quán rộng, thoáng mát", "ambiance", 1),
("decor nhẹ nhàng, view đẹp", "ambiance", 1),
("không gian đẹp mắt, hợp trend", "ambiance", 1),
("ngồi thoải mái, dễ chịu", "ambiance", 1),
("quán sáng sủa, sạch sẽ", "ambiance", 1),
("view đẹp, quán dễ chịu", "ambiance", 1),
("decor hiện đại, gọn gàng", "ambiance", 1),
("không gian rộng, ngồi thoải mái", "ambiance", 1),
("ngồi thư giãn, quán yên tĩnh", "ambiance", 1),
("quán xinh xắn, dễ chịu", "ambiance", 1),
("view đẹp, ánh sáng hợp lý", "ambiance", 1),
("decor tinh tế, dễ chịu", "ambiance", 1),
("không gian trong lành, view đẹp", "ambiance", 1),
("ngồi uống rất thoải mái", "ambiance", 1),
("quán rộng, thoáng đãng", "ambiance", 1),
("decor đẹp, quán dễ chịu", "ambiance", 1),
("view hợp chụp ảnh, dễ chịu", "ambiance", 1),
("không gian đẹp, sáng sủa", "ambiance", 1),
("ngồi thoải mái, view đẹp", "ambiance", 1),
("quán trang trí đẹp, dễ chịu", "ambiance", 1),
("decor hài hòa, quán xinh", "ambiance", 1),
("không gian yên tĩnh, dễ chịu", "ambiance", 1),
("ngồi thư giãn, view đẹp", "ambiance", 1),
("không gian quán rất thoải mái", "ambiance", 1),
("decor đẹp, tạo cảm giác dễ chịu", "ambiance", 1),
("quán rộng rãi, thoáng mát", "ambiance", 1),
("ánh sáng và âm nhạc hài hòa", "ambiance", 1),
("không gian ấm cúng, dễ thư giãn", "ambiance", 1),
("quán sạch sẽ, bài trí tinh tế", "ambiance", 1),
("chỗ ngồi thoải mái, không chật chội", "ambiance", 1),
("âm nhạc nhẹ nhàng, thư giãn", "ambiance", 1),
("không gian quán sang trọng và thoáng", "ambiance", 1),
("decor quán sáng sủa, bắt mắt", "ambiance", 1),
("quán có góc sống ảo đẹp", "ambiance", 1),
("ánh sáng ấm áp, dễ chịu khi ngồi lâu", "ambiance", 1),
("không gian quán yên tĩnh, dễ trò chuyện", "ambiance", 1),
("bài trí tinh tế, tạo cảm giác thoải mái", "ambiance", 1),
("quán rộng, thoáng, cảm giác rất dễ chịu", "ambiance", 1),
("không gian trong lành, dễ hít thở", "ambiance", 1),
("decor quán sang trọng, không rối mắt", "ambiance", 1),
("quán đẹp, dễ chịu khi ngồi lâu", "ambiance", 1),
("âm nhạc nhẹ nhàng, không quá ồn", "ambiance", 1),
("không gian quán thoải mái, dễ tận hưởng đồ uống", "ambiance", 1),
("không gian quán rộng rãi, ánh sáng tự nhiên dễ chịu", "ambiance", 1),
("view đẹp, góc sống ảo hợp lý", "ambiance", 1),
("decor nhẹ nhàng, tạo cảm giác thư giãn", "ambiance", 1),
("ngồi lâu vẫn thoải mái, bàn ghế vừa vặn", "ambiance", 1),
("quán ấm cúng, âm nhạc nhẹ nhàng dễ chịu", "ambiance", 1),
("không gian thoáng, cây xanh nhiều, nhìn rất dễ chịu", "ambiance", 1),
("decor tinh tế, sạch sẽ và gọn gàng", "ambiance", 1),
("ánh sáng hài hòa, cảm giác rất dễ thư giãn", "ambiance", 1),
("view mở, quán rộng rãi, ngồi lâu vẫn thoải mái", "ambiance", 1),
("quán sang trọng, bài trí đẹp, tạo cảm giác dễ chịu", "ambiance", 1),

# ===== Neutral =====
("không gian tạm ổn", "ambiance", 0),
("decor bình thường", "ambiance", 0),
("quán nhìn không xấu nhưng cũng không đẹp", "ambiance", 0),
("ngồi được, không quá thoải mái", "ambiance", 0),
("không gian không ấn tượng", "ambiance", 0),
("quán bố trí đơn giản", "ambiance", 0),
("không gian trung bình", "ambiance", 0),
("decor vừa mắt nhưng không đặc biệt", "ambiance", 0),
("không gian không quá rộng", "ambiance", 0),
("ngồi ổn, không quá khó chịu", "ambiance", 0),
("view bình thường", "ambiance", 0),
("không gian đủ dùng", "ambiance", 0),
("decor vừa phải", "ambiance", 0),
("quán trang trí đơn giản", "ambiance", 0),
("không gian không gây ấn tượng", "ambiance", 0),
("ngồi bình thường", "ambiance", 0),
("không gian vừa đủ thoải mái", "ambiance", 0),
("quán trang trí không nổi bật", "ambiance", 0),
("decor không quá đặc sắc", "ambiance", 0),
("không gian tạm ổn, không quá xấu", "ambiance", 0),
("view không quá nổi bật", "ambiance", 0),
("quán ổn nhưng không đẹp lắm", "ambiance", 0),
("không gian trung bình, không quá thoải mái", "ambiance", 0),
("decor bình thường, không gây ấn tượng", "ambiance", 0),
("ngồi vừa được", "ambiance", 0),
("không gian vừa đủ rộng", "ambiance", 0),
("quán không quá ồn cũng không quá yên tĩnh", "ambiance", 0),
("decor trung bình", "ambiance", 0),
("không gian đủ dùng, không quá đẹp", "ambiance", 0),
("ngồi được nhưng không quá thoải mái", "ambiance", 0),
("không gian không quá xấu", "ambiance", 0),
("quán trung bình", "ambiance", 0),
("decor không nổi bật", "ambiance", 0),
("không gian vừa đủ", "ambiance", 0),
("ngồi bình thường, không khó chịu", "ambiance", 0),
("view bình thường, không ấn tượng", "ambiance", 0),
("quán không quá đẹp, cũng không quá xấu", "ambiance", 0),
("không gian đủ dùng, decor trung bình", "ambiance", 0),
("ngồi ổn, không quá thoải mái", "ambiance", 0),
("quán trang trí tạm ổn", "ambiance", 0),
("không gian không gây khó chịu", "ambiance", 0),
("decor vừa phải, không nổi bật", "ambiance", 0),
("ngồi bình thường, không quá dễ chịu", "ambiance", 0),
("view không quá đẹp", "ambiance", 0),
("không gian đủ dùng, không quá rộng", "ambiance", 0),
("quán ổn nhưng không đặc sắc", "ambiance", 0),
("decor trung bình, không gây ấn tượng", "ambiance", 0),
("ngồi vừa đủ thoải mái", "ambiance", 0),
("không gian không nổi bật", "ambiance", 0),
("view và decor bình thường", "ambiance", 0),
("quán trung bình, không quá nổi bật", "ambiance", 0),
("không gian vừa đủ, decor trung bình", "ambiance", 0),
("ngồi ổn, không quá khó chịu", "ambiance", 0),
("không gian không gây ấn tượng mạnh", "ambiance", 0),
("decor tạm ổn", "ambiance", 0),
("không gian quán bình thường", "ambiance", 0),
("decor đơn giản, không nổi bật", "ambiance", 0),
("quán vừa đủ rộng, không quá chật", "ambiance", 0),
("ánh sáng và âm nhạc bình thường", "ambiance", 0),
("không gian không quá ấm cúng nhưng cũng không khó chịu", "ambiance", 0),
("quán sạch nhưng không đặc sắc", "ambiance", 0),
("chỗ ngồi đủ thoải mái", "ambiance", 0),
("không gian tạm ổn, đủ để thưởng thức đồ uống", "ambiance", 0),
("bài trí quán bình thường, không nổi bật", "ambiance", 0),
("quán không quá đẹp, không quá xấu", "ambiance", 0),
("ánh sáng quán vừa phải", "ambiance", 0),
("quán vừa đủ yên tĩnh", "ambiance", 0),
("decor đơn giản, dễ chịu nhưng không ấn tượng", "ambiance", 0),
("không gian không tạo cảm giác đặc biệt", "ambiance", 0),
("quán tạm ổn, không gây phiền hà", "ambiance", 0),
("không gian vừa đủ rộng, không thoáng lắm", "ambiance", 0),
("quán đủ sạch nhưng không quá bắt mắt", "ambiance", 0),
("âm nhạc không quá ồn, không quá nhẹ", "ambiance", 0),
("decor không nổi bật nhưng chấp nhận được", "ambiance", 0),
("không gian quán vừa đủ, không tốt cũng không tệ", "ambiance", 0),
("không gian quán bình thường, vừa đủ để thưởng thức đồ uống", "ambiance", 0),
("decor đơn giản, không nổi bật nhưng chấp nhận được", "ambiance", 0),
("ngồi được, không quá thoải mái cũng không quá khó chịu", "ambiance", 0),
("view quán trung bình, không quá xấu cũng không quá đẹp", "ambiance", 0),
("quán sạch nhưng ánh sáng hơi tối", "ambiance", 0),
("decor vừa mắt, không gây ấn tượng mạnh", "ambiance", 0),
("không gian vừa đủ rộng, di chuyển bình thường", "ambiance", 0),
("âm nhạc và ánh sáng ở mức ổn, không quá nổi bật", "ambiance", 0),
("quán tạm ổn, đủ để ngồi lâu nhưng không quá thoải mái", "ambiance", 0),
("decor ổn nhưng không hợp gu đặc biệt", "ambiance", 0),

# ===== Negative =====
("quán ồn quá", "ambiance", -1),
("không gian chật chội", "ambiance", -1),
("ngồi rất khó chịu", "ambiance", -1),
("bàn ghế cũ nát", "ambiance", -1),
("quán nóng bức", "ambiance", -1),
("không gian bí bách", "ambiance", -1),
("decor rối mắt", "ambiance", -1),
("không gian không đẹp", "ambiance", -1),
("view xấu", "ambiance", -1),
("ngồi khó chịu vì bàn ghế cũ", "ambiance", -1),
("quán lộn xộn", "ambiance", -1),
("không gian bẩn", "ambiance", -1),
("decor lỗi thời", "ambiance", -1),
("không gian chật, khó chịu", "ambiance", -1),
("quán đông và ồn", "ambiance", -1),
("không gian quá nhỏ", "ambiance", -1),
("ngồi rất bất tiện", "ambiance", -1),
("quán trông xập xệ", "ambiance", -1),
("decor không hợp mắt", "ambiance", -1),
("không gian thiếu sáng", "ambiance", -1),
("view không đẹp, tường trống trơn", "ambiance", -1),
("ngồi gần máy lạnh nhưng vẫn nóng", "ambiance", -1),
("quán bừa bộn", "ambiance", -1),
("không gian khiến mình khó chịu", "ambiance", -1),
("bàn ghế ọp ẹp", "ambiance", -1),
("decor rườm rà, nhìn khó chịu", "ambiance", -1),
("quán ồn ào, không yên tĩnh", "ambiance", -1),
("không gian tù túng", "ambiance", -1),
("ngồi bất tiện, không thoải mái", "ambiance", -1),
("view xấu, không hợp chụp ảnh", "ambiance", -1),
("quán nóng nực, bí bách", "ambiance", -1),
("không gian thiếu gọn gàng", "ambiance", -1),
("decor cũ kỹ", "ambiance", -1),
("quán chật, khó di chuyển", "ambiance", -1),
("ngồi không thoải mái, ghế cứng", "ambiance", -1),
("view không đẹp, xung quanh lộn xộn", "ambiance", -1),
("quán không sạch sẽ", "ambiance", -1),
("decor lỗi thời, không thẩm mỹ", "ambiance", -1),
("không gian bí, nóng và ồn", "ambiance", -1),
("ngồi bất tiện, không thoải mái", "ambiance", -1),
("quán ồn, không thể nói chuyện", "ambiance", -1),
("không gian nhỏ, bừa bộn", "ambiance", -1),
("bàn ghế cũ, decor rối mắt", "ambiance", -1),
("quán nóng, không thoáng", "ambiance", -1),
("view xấu, quán chật", "ambiance", -1),
("không gian bí bách, ghế cứng", "ambiance", -1),
("decor không hợp mắt, lộn xộn", "ambiance", -1),
("ngồi khó chịu, không thoải mái", "ambiance", -1),
("quán đông, ồn ào", "ambiance", -1),
("không gian không gọn gàng", "ambiance", -1),
("bàn ghế ọp ẹp, view xấu", "ambiance", -1),
("decor lỗi thời, không đẹp", "ambiance", -1),
("quán chật, không thoải mái", "ambiance", -1),
("ngồi bất tiện, view xấu", "ambiance", -1),
("không gian lộn xộn, nóng bức", "ambiance", -1),
("quán bẩn, ghế cứng", "ambiance", -1),
("decor rối mắt, không đẹp", "ambiance", -1),
("ngồi khó chịu, quán chật", "ambiance", -1),
("view xấu, không gian bí", "ambiance", -1),
("quán ồn, decor rối mắt", "ambiance", -1),
("quán chật chội, ngột ngạt", "ambiance", -1),
("ánh sáng quá tối, khó chịu", "ambiance", -1),
("âm nhạc quá ồn, không thư giãn", "ambiance", -1),
("không gian bừa bộn, cảm giác khó chịu", "ambiance", -1),
("decor xấu, lộn xộn", "ambiance", -1),
("chỗ ngồi không thoải mái", "ambiance", -1),
("quán thiếu ánh sáng, không dễ chịu", "ambiance", -1),
("không gian quá đông, ồn ào", "ambiance", -1),
("quán hẹp, khó di chuyển", "ambiance", -1),
("bài trí kém, không hợp mắt", "ambiance", -1),
("âm nhạc quá chói tai, khó tập trung", "ambiance", -1),
("không gian bừa bộn, đồ đạc lộn xộn", "ambiance", -1),
("quán nóng hoặc bí, ngồi không thoải mái", "ambiance", -1),
("ánh sáng lóa, không dễ chịu", "ambiance", -1),
("decor lỗi thời, tạo cảm giác tệ", "ambiance", -1),
("quán chật, ngột ngạt, khó chịu khi ngồi lâu", "ambiance", -1),
("âm nhạc quá ồn, khó trò chuyện", "ambiance", -1),
("không gian lộn xộn, bừa bộn", "ambiance", -1),
("quán thiếu sạch sẽ, tạo cảm giác khó chịu", "ambiance", -1),
("decor không hài hòa, gây khó chịu", "ambiance", -1),
("quán hơi chật, cảm giác bí bách khi ngồi lâu", "ambiance", -1),
("ghế hơi cứng, ngồi lâu thấy mỏi", "ambiance", -1),
("decor rối mắt, ánh sáng chưa hợp lý", "ambiance", -1),
("âm nhạc hơi ồn, khó tập trung nói chuyện", "ambiance", -1),
("không gian tối, hơi ngột ngạt nhưng còn chịu được", "ambiance", -1),
("view không đẹp, chỗ ngồi không thoải mái", "ambiance", -1),
("quán đông, hơi ồn nhưng vẫn ổn với vài người", "ambiance", -1),
("decor lỗi thời, không hợp mắt nhưng sạch sẽ", "ambiance", -1),
("ngồi lâu thấy khó chịu vì bàn ghế nhỏ", "ambiance", -1),
("không gian hơi bí, di chuyển khó chịu", "ambiance", -1),
]

TRAIN_DATA = TRAIN_DATA * 3