# Generated by Django 6.0 on 2025-12-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_contact_cafeshop_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeshop',
            name='avg_ambiance_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cafeshop',
            name='avg_drink_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cafeshop',
            name='avg_price_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cafeshop',
            name='avg_service_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='sentiment_ambiance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='sentiment_drink',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='sentiment_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='sentiment_service',
            field=models.IntegerField(default=0),
        ),
    ]
