# Generated by Django 5.2.8 on 2025-12-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_contact_cafeshop_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeshop',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cafeshop',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
