# Generated by Django 5.2.8 on 2025-12-15 11:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_cafeshop_latitude_cafeshop_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeshop',
            name='rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
