# Generated by Django 6.0 on 2025-12-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_shopviewlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopviewlog',
            name='last_viewed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
