# Generated by Django 5.2.8 on 2025-12-15 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_cafeshop_rating'),
        ('shops', '0005_alter_shopviewlog_last_viewed'),
    ]

    operations = [
    ]
