# Generated by Django 5.2.8 on 2025-12-22 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_merge_20251216_0020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cafeshop',
            old_name='avg_ambiance_score',
            new_name='avg_ambiance',
        ),
        migrations.RenameField(
            model_name='cafeshop',
            old_name='avg_drink_score',
            new_name='avg_drink',
        ),
        migrations.RenameField(
            model_name='cafeshop',
            old_name='avg_price_score',
            new_name='avg_price',
        ),
        migrations.RenameField(
            model_name='cafeshop',
            old_name='avg_service_score',
            new_name='avg_service',
        ),
    ]
